import { Behaviour, Text, registerBinaryType, serializable } from "@needle-tools/engine";
import { SendBuffer_Model } from "./SendBuffer_Model";
import { Builder } from "flatbuffers";

// NOTICE: to utilize binary messages from a npmdef, you need to install the flatbuffers package @2.0.4 in your project

// needs to be 4 letters exactly, a specification of flatbuffers
const msgId = "MESG";

// Register the Model factory with the message ID, so a handler registered with beginListenBinary can intersct it
// The SendBuffer_Model is generated by flatbuffer CLI utility called flatc awailable on github (https://github.com/google/flatbuffers/releases)
// The Scheme is defined in the SendBuffer_Model.fbs file and the utility generates the SendBuffer_Model.ts file which we use below.
registerBinaryType(msgId, SendBuffer_Model.getRootAsSendBuffer_Model);

export class SendBufferExample extends Behaviour {
    @serializable(Text)
    label?: Text;

    // we need to store the handler that we register so we can unregister it as well
    handler?: any;

    onEnable() {
        this.handler ??= this.recieveBuffer.bind(this); //a callback needs to be binded to this instance
        this.context.connection.beginListenBinary(msgId, this.handler); 
    }

    onDisable() {
        this.context.connection.stopListenBinary(msgId, this.handler);
    }

    recieveBuffer(receivedModel: SendBuffer_Model) {
        if(this.label)
            this.label.text = receivedModel.message() || "";
    }

    sendBuffer() {        
        // With flatbuffers we need to create values first and then insert them into hiearchy.
        // So the order of the keywords you should call in flatbuffer workflow is: create, start, add, end, finish
        // In other words, first we add unique values and later we define the place they have in the hiearchy.

        // maintains a binary buffer that is later sent
        const builder = new Builder(0);

        // create values and save their poistions in the buffer
        const guidOffeset = builder.createString(this.guid);
        const dontSaveOffset = true; // booleans don't need to be created
        const messageOffset = builder.createString(this.getExampleMessage());

        // Add the positions of the previously created values to fit the scheme's structure
        SendBuffer_Model.startSendBuffer_Model(builder);
        SendBuffer_Model.addGuid(builder, guidOffeset);
        SendBuffer_Model.addDontSave(builder, dontSaveOffset);
        SendBuffer_Model.addMessage(builder, messageOffset);
        const endPos = SendBuffer_Model.endSendBuffer_Model(builder);
        builder.finish(endPos, msgId); // add the MsgID to the flat buffer so it can be identified upon reciving

        // send
        const payload = builder.asUint8Array();
        this.context.connection.sendBinary(payload);
    }

    getExampleMessage() { return `Hello, it is ${new Date(Date.now()).toLocaleTimeString()}!`; }
}