/* eslint-disable */
import { TypeStore } from "@needle-tools/engine"

// Import types
import { AspectRatioFitterUI } from "../AspectRatioFitterUI.js";
import { CameraGoal } from "../CameraGoal.js";
import { CameraLayer } from "../CameraLayer.js";
import { Cannon } from "../Cannon.js";
import { RandomColor } from "../ChangeColor.js";
import { ChangeColorOnCollision } from "../ChangeColorOnCollision.js";
import { IncreaseShaderSpeedOverTime } from "../ChangeCustomShaderProperty.js";
import { ClickButton } from "../ClickButton.js";
import { ClickToReset } from "../ClickToReset.js";
import { DepthOfFieldController } from "../DepthOfFieldController.js";
import { DisableEnvironmentLight } from "../DisableEnvironment.js";
import { EmitParticlesOnClick } from "../EmitParticlesOnClick.js";
import { EnforceParameters } from "../EnforceParameters.js";
import { HTMLButtonClick } from "../HTMLButtonEvent.js";
import { HTMLMenu } from "../HTMLMenu.js";
import { IFrameContent } from "../IFrameContent.js";
import { ImageTrackingDownloadUI } from "../ImageTrackingDownloadUI.js";
import { LODGroupUI } from "../LODGroupUI.js";
import { Networking_ClickToChangeColor } from "../Networking.js";
import { Networking_StringArray } from "../Networking.js";
import { Networking_Object } from "../Networking.js";
import { PerformanceSettings } from "../PerformanceSettings.js";
import { Photographer } from "../Photographer.js";
import { PhysicsCollision } from "../PhysicsCollision.js";
import { PhysicsTrigger } from "../PhysicsCollision.js";
import { PlayAnimationOnCollision } from "../PlayAnimationOnCollision.js";
import { PlayAnimationOnTrigger } from "../PlayAnimationOnTrigger.js";
import { PlayAudioOnCollision } from "../PlayAudioOnCollision.js";
import { ResetAnimationsForXR } from "../ResetAnimationsForXR.js";
import { ResponsiveContent } from "../ResponsiveContent.js";
import { LoadingSceneRoot } from "../SceneSwitcher.js";
import { SceneLoadingEvents } from "../SceneSwitcher.js";
import { SceneSwitcherControls } from "../SceneSwitcherControls.js";
import { SetBackfaceCulling } from "../SetBackfaceCulling.js";
import { ShowBalloonMessage } from "../ShowBalloonMessage.js";
import { SimpleLeaderboard } from "../SimpleLeaderboard.js";
import { StartPosition } from "../StartPosition.js";
import { AutoReset } from "../StartPosition.js";
import { SyncedRoomUI } from "../SyncedRoomUI.js";
import { TimedSpawn } from "../TimedSpawn.js";
import { TopMenu } from "../TopMenu.js";
import { VideoBackground } from "../VideoBackground.js";
import { ResetPositionOnInterval } from "../VisibilitySamples.js";
import { ToggleVisibility } from "../VisibilitySamples.js";
import { WireframeMaterial } from "../WireframeMaterial.js";
import { XRLifecycleEvents } from "../XRLifecycleEvents.js";
import { WebXRBodyTracking } from "../BodyTracking/WebXRBodyTracking.js";
import { Arrow } from "../Bow & Arrow/Arrow.js";
import { ArrowShooting } from "../Bow & Arrow/ArrowShooting.js";
import { BowArrowTarget } from "../Bow & Arrow/BowArrowTarget.js";
import { BowTargetSpawner } from "../Bow & Arrow/BowTargetSpawner.js";
import { CustomDepthSensing } from "../Depth Sensing/CustomDepthSensing.js";
import { DeviceDetection } from "../Device Detection/DeviceDetection.js";
import { CustomUSDSettings } from "../EverywhereActions/CustomUSDSettings.js";
import { FadeOnProximity } from "../EverywhereActions/FadeOnProximity.js";
import { PlayAnimationOnProximity } from "../EverywhereActions/PlayAnimationOnProximity.js";
import { SoundOnProximity } from "../EverywhereActions/SoundOnProximity.js";
import { EverywhereConfigurator } from "../EverywhereConfigurator/EverywhereConfigurator.js";
import { ButtonAndTextFiller } from "../Gallery/ButtonAndTextFiller.js";
import { GalleryManager } from "../Gallery/GalleryManager.js";
import { GalleryPOI } from "../Gallery/GalleryPOI.js";
import { GalleryUIItem } from "../Gallery/GalleryUI.js";
import { GalleryUICategory } from "../Gallery/GalleryUI.js";
import { GalleryUI } from "../Gallery/GalleryUI.js";
import { MaterialXAsset } from "../Material X/MaterialXAsset.js";
import { ShadeWithMaterialX } from "../Material X/MaterialXNodeGraph.js";
import { SyncedPlayableDirector } from "../Networking/SyncedPlayableDirector.js";
import { ConsumeAllPointers } from "../PointerHandlers/ConsumeAllPointers.js";
import { ReflectionsSwitcher } from "../ReflectionProbes/ReflectionsSwitcher.js";
import { VariantInfo } from "../Variants/VariantInfo.js";
import { VariantSwitcher } from "../Variants/VariantSwitcher.js";

// Register types
TypeStore.add("AspectRatioFitterUI", AspectRatioFitterUI);
TypeStore.add("CameraGoal", CameraGoal);
TypeStore.add("CameraLayer", CameraLayer);
TypeStore.add("Cannon", Cannon);
TypeStore.add("RandomColor", RandomColor);
TypeStore.add("ChangeColorOnCollision", ChangeColorOnCollision);
TypeStore.add("IncreaseShaderSpeedOverTime", IncreaseShaderSpeedOverTime);
TypeStore.add("ClickButton", ClickButton);
TypeStore.add("ClickToReset", ClickToReset);
TypeStore.add("DepthOfFieldController", DepthOfFieldController);
TypeStore.add("DisableEnvironmentLight", DisableEnvironmentLight);
TypeStore.add("EmitParticlesOnClick", EmitParticlesOnClick);
TypeStore.add("EnforceParameters", EnforceParameters);
TypeStore.add("HTMLButtonClick", HTMLButtonClick);
TypeStore.add("HTMLMenu", HTMLMenu);
TypeStore.add("IFrameContent", IFrameContent);
TypeStore.add("ImageTrackingDownloadUI", ImageTrackingDownloadUI);
TypeStore.add("LODGroupUI", LODGroupUI);
TypeStore.add("Networking_ClickToChangeColor", Networking_ClickToChangeColor);
TypeStore.add("Networking_StringArray", Networking_StringArray);
TypeStore.add("Networking_Object", Networking_Object);
TypeStore.add("PerformanceSettings", PerformanceSettings);
TypeStore.add("Photographer", Photographer);
TypeStore.add("PhysicsCollision", PhysicsCollision);
TypeStore.add("PhysicsTrigger", PhysicsTrigger);
TypeStore.add("PlayAnimationOnCollision", PlayAnimationOnCollision);
TypeStore.add("PlayAnimationOnTrigger", PlayAnimationOnTrigger);
TypeStore.add("PlayAudioOnCollision", PlayAudioOnCollision);
TypeStore.add("ResetAnimationsForXR", ResetAnimationsForXR);
TypeStore.add("ResponsiveContent", ResponsiveContent);
TypeStore.add("LoadingSceneRoot", LoadingSceneRoot);
TypeStore.add("SceneLoadingEvents", SceneLoadingEvents);
TypeStore.add("SceneSwitcherControls", SceneSwitcherControls);
TypeStore.add("SetBackfaceCulling", SetBackfaceCulling);
TypeStore.add("ShowBalloonMessage", ShowBalloonMessage);
TypeStore.add("SimpleLeaderboard", SimpleLeaderboard);
TypeStore.add("StartPosition", StartPosition);
TypeStore.add("AutoReset", AutoReset);
TypeStore.add("SyncedRoomUI", SyncedRoomUI);
TypeStore.add("TimedSpawn", TimedSpawn);
TypeStore.add("TopMenu", TopMenu);
TypeStore.add("VideoBackground", VideoBackground);
TypeStore.add("ResetPositionOnInterval", ResetPositionOnInterval);
TypeStore.add("ToggleVisibility", ToggleVisibility);
TypeStore.add("WireframeMaterial", WireframeMaterial);
TypeStore.add("XRLifecycleEvents", XRLifecycleEvents);
TypeStore.add("WebXRBodyTracking", WebXRBodyTracking);
TypeStore.add("Arrow", Arrow);
TypeStore.add("ArrowShooting", ArrowShooting);
TypeStore.add("BowArrowTarget", BowArrowTarget);
TypeStore.add("BowTargetSpawner", BowTargetSpawner);
TypeStore.add("CustomDepthSensing", CustomDepthSensing);
TypeStore.add("DeviceDetection", DeviceDetection);
TypeStore.add("CustomUSDSettings", CustomUSDSettings);
TypeStore.add("FadeOnProximity", FadeOnProximity);
TypeStore.add("PlayAnimationOnProximity", PlayAnimationOnProximity);
TypeStore.add("SoundOnProximity", SoundOnProximity);
TypeStore.add("EverywhereConfigurator", EverywhereConfigurator);
TypeStore.add("ButtonAndTextFiller", ButtonAndTextFiller);
TypeStore.add("GalleryManager", GalleryManager);
TypeStore.add("GalleryPOI", GalleryPOI);
TypeStore.add("GalleryUIItem", GalleryUIItem);
TypeStore.add("GalleryUICategory", GalleryUICategory);
TypeStore.add("GalleryUI", GalleryUI);
TypeStore.add("MaterialXAsset", MaterialXAsset);
TypeStore.add("ShadeWithMaterialX", ShadeWithMaterialX);
TypeStore.add("SyncedPlayableDirector", SyncedPlayableDirector);
TypeStore.add("ConsumeAllPointers", ConsumeAllPointers);
TypeStore.add("ReflectionsSwitcher", ReflectionsSwitcher);
TypeStore.add("VariantInfo", VariantInfo);
TypeStore.add("VariantSwitcher", VariantSwitcher);
